version: "3.8"
services:
  nginx:
    container_name: hk-nginx
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
    volumes:
      - .default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    image: ghcr.io/alexmeh96/spring-app-image:${DOCKER_TAG}
    container_name: "app"
    restart: always
    ports:
      - 8080:8080